FROM tensorflow/tensorflow:1.14.0-py3

ENV LANG=C.UTF-8
ENV PYTHONUNBUFFERED=1
RUN apt-get update
COPY ./requirements.txt /requirements.txt
RUN pip3 install -r requirements.txt

COPY ./entrypoint.sh /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

#RUN mkdir /gpt-2
#WORKDIR /gpt-2
#ADD . /gpt-2
COPY ./download_model.py /download_model.py
#RUN python3 download_model.py 124M
#RUN python3 download_model.py 355M
#RUN python3 download_model.py 774M
#RUN python3 download_model.py 1558M
WORKDIR /gpt-2
